name: listing
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  excel: ^4.0.6
  firebase_auth: ^6.5.1
  firebase_core: ^4.9.0
  firebase_database: ^12.4.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.3.0
  get: ^4.7.3
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  share_plus: ^13.1.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff" # Ganti dengan kode warna hex sesuai tema Anda
    theme_color: "#00B4D8"      # Ganti dengan warna tema utama

flutter_native_splash:
  color: "#ffffff"              # Warna background layar awal
  image: "assets/logo.png"
  android_12:
    image: "assets/logo.png"
    color: "#ffffff"
  web: false                    # Set false karena web punya sistem loading sendiri
