// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAby69N8ATjf0Q9yuoMdYmk5NszqS4sgFk',
    appId: '1:499686733885:web:32030a93237014fd0dd254',
    messagingSenderId: '499686733885',
    projectId: 'listing-inventaris',
    authDomain: 'listing-inventaris.firebaseapp.com',
    databaseURL: 'https://listing-inventaris-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'listing-inventaris.firebasestorage.app',
    measurementId: 'G-YTWZNEH7PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBidkIyk0mKxml70RO53Obi-DoC3CBo5Wg',
    appId: '1:499686733885:android:6f1ec589a490a5140dd254',
    messagingSenderId: '499686733885',
    projectId: 'listing-inventaris',
    databaseURL: 'https://listing-inventaris-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'listing-inventaris.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm__yy7A9BqYlAj0OIiK2TYVTUhL5bqgI',
    appId: '1:499686733885:ios:1f97b714c26c09b40dd254',
    messagingSenderId: '499686733885',
    projectId: 'listing-inventaris',
    databaseURL: 'https://listing-inventaris-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'listing-inventaris.firebasestorage.app',
    androidClientId: '499686733885-eq2hk772fagcm2kunt5snsmg926hbl6i.apps.googleusercontent.com',
    iosClientId: '499686733885-63rmc9gm314hj284esi52vum99l99rfd.apps.googleusercontent.com',
    iosBundleId: 'com.tk.listing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm__yy7A9BqYlAj0OIiK2TYVTUhL5bqgI',
    appId: '1:499686733885:ios:1f97b714c26c09b40dd254',
    messagingSenderId: '499686733885',
    projectId: 'listing-inventaris',
    databaseURL: 'https://listing-inventaris-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'listing-inventaris.firebasestorage.app',
    androidClientId: '499686733885-eq2hk772fagcm2kunt5snsmg926hbl6i.apps.googleusercontent.com',
    iosClientId: '499686733885-63rmc9gm314hj284esi52vum99l99rfd.apps.googleusercontent.com',
    iosBundleId: 'com.tk.listing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAby69N8ATjf0Q9yuoMdYmk5NszqS4sgFk',
    appId: '1:499686733885:web:7dab1fe099348fad0dd254',
    messagingSenderId: '499686733885',
    projectId: 'listing-inventaris',
    authDomain: 'listing-inventaris.firebaseapp.com',
    databaseURL: 'https://listing-inventaris-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'listing-inventaris.firebasestorage.app',
    measurementId: 'G-3ZQKJ0W4V2',
  );

}